version: '3.8'

services:
  backend:
    build: .
    container_name: album-fotos-backend
    ports:
      - "8003:80"
    volumes:
      - ./photos:/app/photos
      - ./photos.json:/app/photos.json
    environment:
      - PHOTOS_ROOT=/app/photos
    restart: unless-stopped
